---
- hosts: all
  become: true
  tasks:
   -  name: Install Apache
      apt: name=apache2 state=present update_cache=yes

   -  name: change port to 90
      lineinfile: path=/etc/apache2/ports.conf regexp='^Listen' line='Listen 90'

   -  name: install apache
      service: name=apache2 state=started enabled=yes

      
      
